### ISSUE TITLE
PHP Sample generation: Error from try/catch block

### ISSUE THREAD

**Issue by bshaffer** [googleapis/toolkit#1173]
For some packages (e.g. `google-cloud-php-speech`), composer.json does not install the required `grpc/grpc`, `google/gax`, or `google/proto-client-php` packages. The user ends up with warnings that `$speechClient` doesn't exist. 

```php
try {
    $speechClient = new SpeechClient();
    //...
} finally {
    $speechClient->close();
}
```

```
PHP Notice:  Undefined variable: speechClient in test.php on line 21
PHP Stack trace:
PHP   1. {main}() test.php:0

Notice: Undefined variable: speechClient in test.php on line 21

Call Stack:
    0.0002     358200   1. {main}() test.php:0

PHP Fatal error:  Uncaught Error: Class 'Google\GAX\LongRunning\OperationsClient' not found in vendor/google/cloud-speech/V1/SpeechClient.php:228
Stack trace:
#0 test.php(8): Google\Cloud\Speech\V1\SpeechClient->__construct()
#1 {main}

Next Error: Call to a member function close() on null in test.php:21
Stack trace:
#0 {main}
  thrown in test.php on line 21

Fatal error: Uncaught Error: Class 'Google\GAX\LongRunning\OperationsClient' not found in vendor/google/cloud-speech/V1/SpeechClient.php:228
Stack trace:
#0 test.php(8): Google\Cloud\Speech\V1\SpeechClient->__construct()
#1 {main}

Next Error: Call to a member function close() on null in test.php on line 21

Error: Call to a member function close() on null in test.php on line 21

Call Stack:
    0.0002     358200   1. {main}() test.php:0
```

This highlights two issues:

1. The try/catch block should only exist after the $speechClient object is successfully initialized, to avoid an error in the finally block.
2. When initialized, the client should check for the existence of the dependent classes and throw helpful errors, such as the following:

```php
if (!defined('Grpc\STATUS_OK')) {
    throw new \Exception('Install the grpc extension ' .
        '(pecl install grpc)');
}
if (!class_exists('google\cloud\speech\v1\SpeechGrpcClient')) {
    throw new \Exception('Install the proto client PHP library ' .
        '(composer require google/proto-client-php)');
}
if (!class_exists('Google\GAX\GrpcConstants')) {
    throw new \Exception('Install the GAX library ' .
        '(composer require google/gax)');
}
```

**Comment by eoogbe** [comment]
@michaelbausor Can you add a priority to this?

**Comment by michaelbausor** [comment]
1. Will be fixed in https://github.com/googleapis/toolkit/pull/1747
2. This is fixed in the composer.json files, which now require proto-client-php and gax. The requirement for the grpc extension will be fixed by the http/json transport
