### ISSUE TITLE
`_pageDescriptors` is not defined

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/toolkit#1623]
Testing this branch: https://github.com/googleapis/nodejs-logging/tree/new-gapic

```sh
$ npm run system-test

  Logging
       sinks
         listing sinks
           should list sinks as a stream:
     Uncaught TypeError: Cannot read property 'listSinks' of undefined
      at ConfigServiceV2Client.listSinksStream (src\v2\config_service_v2_client.js:362:33)
      at src\index.js:713:19
      at src\index.js:683:7
      at Immediate.setImmediate (node_modules\google-auto-auth\index.js:161:9)
```

This is the line: https://github.com/googleapis/nodejs-logging/blob/057f37571f1081d91f9a4c89d185b6bed361e3cb/src/v2/config_service_v2_client.js#L362

cc @lukesneeringer

**Comment by stephenplusplus** [comment]
It looks like it should be:

`this._descriptors.page`

Instead of:

`this._pageDescriptors
