### ISSUE TITLE
Unrecognized resource name type error

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/toolkit#1734]
I think that https://github.com/googleapis/toolkit/pull/1692 has introduced a bug in toolkit. When I try to generate pubsub locally with toolkit checked out to (dbbbaa4ce659310d07393e3881c3a259473db0ad), I get the error pasted below.

When I check out the previous commit (bde101fd1927c7a6bc7fb66f28a885253c31d906) I get no errors and generate successfully. This is using local generation with artman 0.5.4 installed, and googleapis checkout out to current head (which is `838aab147a3a3b5c9a198ce7ea4ac71858919975`).

The artman command I am using is: 
`artman --local --config google/pubsub/artman_pubsub.yaml generate php_gapic`

This is also reproducible for other language generation:
`artman --local --config google/pubsub/artman_pubsub.yaml generate java_gapic`

The errors I am seeing is:

```
ERROR: toplevel: Unexpected exception:
java.lang.IllegalArgumentException: Unrecognized resource name type: UNSET_TREATMENT
	at com.google.api.codegen.config.FieldConfig.validate(FieldConfig.java:295)
	at com.google.api.codegen.config.FieldConfig.createFieldConfig(FieldConfig.java:193)
	at com.google.api.codegen.config.FieldConfig.createMessageFieldConfig(FieldConfig.java:113)
	at com.google.api.codegen.config.PageStreamingConfig.createPageStreaming(PageStreamingConfig.java:116)
	at com.google.api.codegen.config.GapicMethodConfig.createMethodConfig(GapicMethodConfig.java:76)
	at com.google.api.codegen.config.GapicInterfaceConfig.createMethodConfigMap(GapicInterfaceConfig.java:234)
	at com.google.api.codegen.config.GapicInterfaceConfig.createInterfaceConfig(GapicInterfaceConfig.java:132)
	at com.google.api.codegen.config.GapicProductConfig.createInterfaceConfigMap(GapicProductConfig.java:335)
	at com.google.api.codegen.config.GapicProductConfig.create(GapicProductConfig.java:147)
	at com.google.api.codegen.CodeGeneratorApi.process(CodeGeneratorApi.java:133)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.CodeGeneratorTool.generate(CodeGeneratorTool.java:120)
	at com.google.api.codegen.CodeGeneratorTool.main(CodeGeneratorTool.java:92)
```

**Comment by michaelbausor** [comment]
I believe this is fixed by https://github.com/googleapis/toolkit/pull/1737. Closing this now, ongoing tracking in https://github.com/googleapis/toolkit/issues/1736
