### ISSUE TITLE
gradlew runVGen fails

### ISSUE THREAD

**Issue by broady** [googleapis/toolkit#179]
```
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
The uploadArchives task was skipped. The privateOssrhUsername and privateOssrhPassword properties need to be set correctly in your ~/.gradle/gradle.properties file in order to upload archives.
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
:compileJava UP-TO-DATE
:processResources
:classes
:runVGen
Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required options: descriptor_set, service_yaml, gapic_yaml
	at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:199)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:130)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at com.google.api.codegen.CodeGeneratorTool.main(CodeGeneratorTool.java:71)
:runVGen FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runVGen'.
> Process 'command '/usr/local/buildtools/java/jdk8-google-v7-64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.16 secs
Exit code 1
```

**Comment by garrettjonesgoogle** [comment]
I think this is an issue with user understanding; the runVGen target requires options to be passed, it is not a simple target with no options.

**Comment by broady** [comment]
Wow, yes. I didn't even read the error.
