### ISSUE TITLE
Config generator should validate input exists

### ISSUE THREAD

**Issue by geigerj** [googleapis/toolkit#423]
### To reproduce:

Run ConfigGeneratorTool with `--service_yaml` flag not pointing to a real file. For example, edit an artman config in the `googleapis` repo to point to a non-existent service yaml, then run GapicConfigPipeline in artman.
### Expected behavior:

ConfigGeneratorTool throws a meaningful exception
### Observed behavior:

Hard-to-debug stack trace with exception that occurs in the api-compiler, rather than toolkit.

```
:runConfigGenException in thread "main" java.lang.NullPointerException
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:246)
    at com.google.api.tools.framework.tools.ToolUtil.sanitizeSourceFiles(ToolUtil.java:159)
    at com.google.api.tools.framework.tools.ModelBuilder.parseConfigFiles(ModelBuilder.java:159)
    at com.google.api.tools.framework.tools.ModelBuilder.setup(ModelBuilder.java:48)
    at com.google.api.tools.framework.tools.ToolDriverBase.setupModel(ToolDriverBase.java:93)
    at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:84)
    at com.google.api.codegen.config.ConfigGeneratorTool.generate(ConfigGeneratorTool.java:74)
    at com.google.api.codegen.config.ConfigGeneratorTool.main(ConfigGeneratorTool.java:62)
```

/cc @shinfan

**Comment by geigerj** [comment]
See #425 for discussion.

**Comment by geigerj** [comment]
I think this was fixed by https://github.com/googleapis/api-compiler/commit/c6d2d33609b60241db80a4015cb0b91b45b28fac. If not, it should probably be tracked in the `api-compiler` repo, rather than here.
