### ISSUE TITLE
[NodeJS][LRO] can't find the metadata or response when it's not imported

### ISSUE THREAD

**Issue by jmuk** [googleapis/toolkit#842]
This might affect other languages, but found this on NodeJS.

For cloud functions API, the LRO metadata is defined at https://github.com/googleapis/googleapis/blob/master/google/cloud/functions/v1beta2/operations.proto, but this proto file is not imported. When generating the GAPIC client with LRO configuring with this, this proto file won't be loaded and therefore it fails with
```
/path/to/google-cloud-node/packages/functions/src/v1beta2/cloud_functions_service_client.js:102
      grpcClients.google.cloud.functions.v1beta2.OperationMetadataV1Beta2.decode),
                                                                         ^

TypeError: Cannot read property 'decode' of undefined
    at new CloudFunctionsServiceClient (/path/to/google-cloud-node/packages/functions/src/v1beta2/cloud_functions_service_client.js:102:74)
    at CloudFunctionsServiceClientBuilder.cloudFunctionsServiceClient (/path/to/google-cloud-node/packages/functions/src/v1beta2/cloud_functions_service_client.js:751:12)
    at Object.<anonymous> (/path/to/google-cloud-node/packages/functions/foo.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

We could fix this by adding the following line to functions.proto
```protobuf
import "google/cloud/functions/v1beta2/operations.proto";
```

I'm not sure this is the right solution.

Theoretically the same thing could happen for the final result type.
This might happen on other languages, although I'm not familiar with them.

**Comment by jmuk** [comment]
@landrito -- please take a look. Cc: @jmdobry

**Comment by landrito** [comment]
I think adding:
```js 
import "google/cloud/functions/v1beta2/operations.proto";
```
to  `functions.proto` is the correct solution to this bug. In Ruby, Node, and Java (I think), the current design of LROs  depends on the metadata and response types either being declared in the service proto, or being a dependency of the service proto.

@garrettjonesgoogle might be good to include in this conversation.

**Comment by garrettjonesgoogle** [comment]
I don't think that missing this import line will cause problems in the Java GAPIC client - it might have to be tried to be sure, though.

**Comment by landrito** [comment]
Resolved by this commit: https://github.com/googleapis/googleapis/commit/a4277e6624c6d3efbbb6246eeaa3330568ed642c
